---
version: '2'
services:
  redis:
    networks:
      default:
    image: redis:4.0.11-alpine
    container_name: order-service-redis
    mem_limit: 128m
    command: redis-server --requirepass redis
    ports: 
      - "6379:6379"   
networks:
  default:
    external:
      name: order-network
